version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

    commands:
      # Install dependencies
      - cd react-website
      - npm install

  build:
    commands:
      # Run build script
      - npm run build
      - pwd
      - ls

artifacts:
  files:
    # - 'react-website/public/**/*'
    # - 'react-website/src/**/*'
    # - 'react-website/package.json'
    - '**/*'

  # base-directory: build
