version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

    commands:
      # Install dependencies
      - cd react-website
      - npm install

  pre_build:
    commands:
      - cd ..

  build:
    commands:
      # Run build script
      - cd react-website
      - npm run build
  
  post_build:
    commands:
      - cd ..

artifacts:
  # include all files required to run application
  # we include only the static build files
  files:
    - '**/*'
  base-directory: 'build'
