version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

    commands:
      # Install dependencies
      - npm install

      # Install yarn
      - echo installing yarn
      - npm install yarn
      - yarn add eslint-config-react-app

  build:
    commands:
      - echo Building...
      - yarn build

artifacts:
  files:
    - "**/*"

  # discard-paths: yes
  base-directory: build
